### ISSUE TITLE
Use binaries instead of install time build

### ISSUE THREAD

**Issue by mfuentesg** [ameshkov/homebrew-tap#1]
Hi!

I wanted to use your tool, but, once I executed `brew install ...`, it fails because it depends of my local go version.

```
go
build
-ldflags
-X main.VersionString=1.5.1
-trimpath
-o=/usr/local/Cellar/dnslookup/1.5.1/bin/dnslookup

# github.com/lucas-clemente/quic-go/internal/qtls
/Users/m0f05xo/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/lucas-clemente/quic-go@v0.24.0/internal/qtls/go118.go:6:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/ameshkov/homebrew-tap/issues
```

I have an automated process with goreleaser, and instead to build the binary in the "host" it uses the created binaries 
 (reference: https://github.com/mfuentesg/homebrew-tap/blob/master/ksd.rb)

Maybe, it could be helpful

**Comment by ameshkov** [comment]
Hi, the issue is resolved now with using a newer version of dnslookup: https://github.com/ameshkov/homebrew-tap/commit/898d40ea9ce8044d3a2ed9bbc56c91c52897d82a

I am not sure if using binaries is a good idea when it's that easy to avoid it when automating the build seems rather trivial.
